### ISSUE TITLE
Problems with write protected files

### ISSUE THREAD

**Issue by infeo** [cryptomator/dokany-nio-adapter#10]
## Basic Info
**OS:** Windows 10 Pro Ver 1803
**Dokany-Version:** 1.2.0.1000
**Adapter-Version:** commit 5df4f087dd576dc748647d1d6c029673b34e521a

## Description

Write protected files causing "AccessDeniedExceptions" because when opening a file channel the open option `WRITE`  is given into the function. Furthermore they can not be deleted.

**Comment by overheadhunter** [comment]
The question is: why should there be a write-protected ciphertext file in the vault? The only scenario, that I can imagine is:
1. User creates a file on dokany drive
2. User changes file permissions
3. User accesses the file for writing despite write protection (i.e. the exception is correct in this case)

**Comment by infeo** [comment]
Read-only files are now supported by commit 8d9c8e857a0e15030f3ffccbd4e95bb2934d5fc2
