### ISSUE TITLE
Add option to use custom mount options

### ISSUE THREAD

**Issue by infeo** [cryptomator/dokany-nio-adapter#30]
Adapter version: 1.1.8

Currently a lot of options to mount a volume are hardcoded, see [MountFactory,java](https://github.com/cryptomator/dokany-nio-adapter/blob/develop/src/main/java/org/cryptomator/frontend/dokany/MountFactory.java)

For a more flexible approach we should introduce an additional mount method and an option parser.

**Comment by overheadhunter** [comment]
Well you parse strings, but the mount options are not yet used in any way by the MountFactory. Atm this is not usable in Cryptomator.

**Comment by infeo** [comment]
closed by 686434ffe27afc580bdc041dd6c153895c6997a6
