### ISSUE TITLE
Very slow writing speed / Always synchronised writing

### ISSUE THREAD

**Issue by infeo** [cryptomator/dokany-nio-adapter#32]
## Basic Info
Commit: cc16727febcbf2c297b3e296ff2765b4da81a2b6 
Dokan Version: 1.3.1000

## Description
Using the mirror test class shows that the maximum writing speed of the adpater decreased by almost 95% (200Mb/s to meager 10 Mb/s). This should be fixed ASAP.

## Explanation
The reason for this performance drop lies in commit afbef5d9a6b269e4e3ffca4d2203e4a6cdcdec68 , where the adapter were enhanced by setting the SYNC open option properly. But this is not true.

First, according to the Microsft documentation of the access mask [`SYNCHRONIZE`](https://docs.microsoft.com/de-de/windows/win32/secauthz/standard-access-rights), this has nothing to do with the Java [StandardOpenOption.SYNC](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/StandardOpenOption.html#SYNC). The first one is for waiting until an (IO) operation is finished while the latter one states that changes must not be chached and directly written to the file system. Actually there is no access mask for wrinting directly to the file.
Second the createOptions `FILE_SYNCHRONOUS_IOALERT` and `FILE_SYNCHRONOUS_NON_IOALERT` are also flags regarding to wait and notifed when an operation is succesful. Only `FILE_WRITE_THROUGH` and `FILE_NO_INTERMEDIATE_BUFFERING` are similar to StandardOpenOption.SYNC.

**Comment by overheadhunter** [comment]
For the record here is some more information regarding the difference between `SYNC` and `SYNCHRONIZE`.

## What SYNC means for Java NIO

In the Java world, `SYNC` is used as a flag during creation of a file handle to request every change to be persisted immediately without caching etc:

> Requires that every update to the file's content or metadata be written synchronously to the underlying storage device.

~[Source](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/StandardOpenOption.html#SYNC)

## What SYNCHRONIZE means for Microsoft

In the Microsoft world, the `SYNCHRONIZE` access right is defined as:

> The right to use the object for synchronization. This enables a thread to wait until the object is in the signaled state.

~ [Source](https://docs.microsoft.com/de-de/windows/win32/secauthz/standard-access-rights)

This sounds a lot like the wait/notify mechanism in the Java world. I.e. the filehandle can be used as a semaphore.

> Each time an I/O operation is started, the operating system sets the file handle to the nonsignaled state. Each time an I/O operation is completed, the operating system sets the file handle to the signaled state.

~ [Source](https://docs.microsoft.com/en-us/windows/win32/fileio/synchronous-and-asynchronous-i-o)

More on this topic can be found [here](https://docs.microsoft.com/en-us/windows/win32/sync/synchronization-and-overlapped-input-and-output).

## How to request uncached write using win32 APIs

What comes closest to the Java `SYNC` flag is probably `FILE_FLAG_WRITE_THROUGH` or `FILE_FLAG_NO_BUFFERING` as defined in the [win32 file API](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea).
