### ISSUE TITLE
Wrong UNC name

### ISSUE THREAD

**Issue by infeo** [cryptomator/dokany-nio-adapter#33]
## Basic Information
Windows: 10 Pro 1903
Adapter: 1.1.10
Dokany: 1.3.1000

## Description
Since commit 727f585decb19a0cd119574b41f2ba70b35ee1e1 also the UNC name of the volume (using the [? notation](https://stackoverflow.com/a/21194605)) mounted with Dokany is given.

This leads to the following (maybe unwanted) feature and a bug.

### Feature
Now the volume is also shown under the network device section on a "Dokan1" computer and accessible with a UNC name.

### Bug
According to the [UNC definition](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/62e862f4-2a51-452e-8eeb-dc4ff5ee33cc) each name starts with `\\`. But using this notation the volume is not accessible from the network view of the windows file manager. With only one leading `\` it works.

**Comment by infeo** [comment]
@overheadhunter what do you think about the feature?

@Liryna Is the bug really a bug? In a search everywhere the "full" notation with two leading `\` was given, but maybe dropping the first slash is a common thing under windows developers and admins.

**Comment by Liryna** [comment]
Hi @infeo ,

This is because of how network providers and IOCTL_REDIR_QUERY_PATH 
are working https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ni-ntifs-ioctl_redir_query_path where the FilePathName is under the form of `\<sharename><path>` with a single `\`

**Comment by infeo** [comment]
Thanks for the information. But it seems like this feature causes currently some bugs, e.g. that the drive is shown _only_ as a network drive and not addtionally. See the linked issues or [in our forum](https://community.cryptomator.org/t/version-1-4-13-drive-not-connected/4047/2).

Thus, I'll remove the UNC name again.
